import Evento from "./Evento.ts";

const eventos: Evento[] = [
  new Evento(
    1,
    [1, 2, 3],
    [1, 2, 3],
    1,
    'Inscripción y pago de programas de posgrado',
    new Date('2023-08-19'),
    new Date('2023-08-25'),
    ["www.google.com"],
    '/imagenes/imagen1.webp',
    'Período de inscripción y pago de colegiatura de los programas de posgrado',
    '/simbologia/1.webp',
    'facultad'
  ),
  new Evento(
    2,
    [],
    [],
    1,
    'Período vacacional de la UASLP',
    new Date('2023-09-01'),
    new Date('2023-09-15'),
    [],
    '/imagenes/imagen2.webp',
    'Período vacacional de la UASLP',
    '/simbologia/2.webp',
    'facultad'
  ),
  new Evento(
    3,
    [],
    [],
    1,
    'Reunión de inicio de semestre con Profesores de la facultad',
    new Date('2023-09-05'),
    new Date('2023-09-05'),
    [],
    '/imagenes/imagen3.webp',
    'Reunión de inicio del semestre con Profesores de la Facultad.',
    '/simbologia/3.webp',
    'facultad'
  ),
  new Evento(
    4,
    [],
    [],
    1,
    'Aplicación del examen general de conocimientos como opción de titulación',
    new Date('2023-09-10'),
    new Date('2023-09-10'),
    [],
    '/imagenes/imagen4.webp',
    'Aplicación del examen general de conocimientos como opción de titulación',
    '/simbologia/4.webp',
    'facultad'
  ),
  new Evento(
    5,
    [],
    [],
    1,
    '1er reunión de información alumnos de nuevo ingreso',
    new Date('2023-09-15'),
    new Date('2023-09-15'),
    [],
    '/imagenes/imagen5.webp',
    '1er reunión de información: Autoridades de la Facultad de Ingeniería con Padres de familia y Alumnos de primer ingreso.',
    '/simbologia/5.webp',
    'facultad'
  ),
  new Evento(
    6,
    [],
    [],
    1,
    'Inicio de clases del semestre',
    new Date('2023-09-19'),
    new Date('2023-09-19'),
    [],
    '/imagenes/imagen6.webp',
    'Inicio de clases del semestre',
    '/simbologia/6.webp',
    'facultad'
  ),
  new Evento(
    7,
    [],
    [],
    1,
    'Periodo de bajas de materias del Departamento Físico Matemáticas',
    new Date('2023-09-25'),
    new Date('2023-09-30'),
    [],
    '/imagenes/imagen7.webp',
    'Período de bajas de materias del Departamento Fisico Matematico',
    '/simbologia/7.webp',
    'facultad'
  ),
  new Evento(
    8,
    [],
    [],
    1,
    'Reunión del Consejo de Posgrado de la Facultad de Ingeniería',
    new Date('2023-10-01'),
    new Date('2023-10-01'),
    [],
    '/imagenes/imagen8.webp',
    'Reunión del Consejo de Posgrado de la Facultad de Ingeniería',
    '/simbologia/8.webp',
    'facultad'
  ),
  new Evento(
    9,
    [],
    [],
    1,
    'Período de altas y bajas de materias del DUI',
    new Date('2023-10-05'),
    new Date('2023-10-10'),
    [],
    '/imagenes/imagen9.webp',
    'Período de altas y bajas de materias del Departamento Universitario de Inglés',
    '/simbologia/9.webp',
    'facultad'
  ),
  new Evento(
    10,
    [],
    [],
    1,
    'Sesión ordinaria del H. Consejo Técnico Consultivo.',
    new Date('2023-10-15'),
    new Date('2023-10-15'),
    [],
    '/imagenes/imagen10.webp',
    'Sesión ordinaria del H. Consejo Técnico Consultivo.',
    '/simbologia/10.webp',
    'facultad'
  ),
  new Evento(
    11,
    [],
    [],
    1,
    'Inicio de cursos del DUI',
    new Date('2023-10-20'),
    new Date('2023-10-20'),
    [],
    '/imagenes/imagen11.webp',
    'Inicio de cursos del Departamento Universitario de Inglés',
    '/simbologia/11.webp',
    'facultad'
  ),
  new Evento(
    12,
    [],
    [],
    1,
    'Día inhábil',
    new Date('2023-11-01'),
    new Date('2023-11-01'),
    [],
    '/imagenes/imagen12.webp',
    'Día inhábil',
    '/simbologia/12.webp',
    'facultad'
  ),
]

export default eventos
