const Evento: { cat_evento_id: number, usuario_id: number, nombre: string, fecha_inicio: Date, fecha_fin: Date, hipervinculos: string[], imagen: string, descripcion: string, simbolo: string } []= [
    {
      cat_evento_id: 1,
      usuario_id: 1,
      nombre: 'Inscripción y pago de programas de posgrado',
      fecha_inicio: new Date('2023-08-19'),
      fecha_fin: new Date('2023-08-25'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen1.webp',
      descripcion: 'Período de inscripción y pago de colegiatura de los programas de posgrado',
      simbolo: './public/simbologia/1.webp',
    },
    {
      cat_evento_id: 2,
      usuario_id: 2,
      nombre: 'Período vacacional de la UASLP',
      fecha_inicio: new Date('2023-09-01'),
      fecha_fin: new Date('2023-09-15'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen2.webp',
      descripcion: 'Período vacacional de la UASLP',
      simbolo: './public/simbologia/2.webp',
    },
    {
      cat_evento_id: 3,
      usuario_id: 3,
      nombre: 'Reunión de inicio de semestre con Profesores de la facultad',
      fecha_inicio: new Date('2023-09-05'),
      fecha_fin: new Date('2023-09-05'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen3.webp',
      descripcion: 'Reunión de inicio del semestre con Profesores de la Facultad.',
      simbolo: './public/simbologia/3.webp',
    },
    {
      cat_evento_id: 4,
      usuario_id: 4,
      nombre: 'Aplicación del examen general de conocimientos como opción de titulación',
      fecha_inicio: new Date('2023-09-10'),
      fecha_fin: new Date('2023-09-10'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen4.webp',
      descripcion: 'Aplicación del examen general de conocimientos como opción de titulación',
      simbolo: './public/simbologia/4.webp',
    },
    {
      cat_evento_id: 5,
      usuario_id: 5,
      nombre: '1er reunión de información alumnos de nuevo ingreso',
      fecha_inicio: new Date('2023-09-15'),
      fecha_fin: new Date('2023-09-15'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen5.webp',
      descripcion: '1er reunión de información: Autoridades de la Facultad de Ingeniería con Padres de familia y Alumnos de primer ingreso.',
      simbolo: './public/simbologia/5.webp',
    },
    {
      cat_evento_id: 6,
      usuario_id: 6,
      nombre: 'Inicio de clases del semestre',
      fecha_inicio: new Date('2023-09-19'),
      fecha_fin: new Date('2023-09-19'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen6.webp',
      descripcion: 'Inicio de clases del semestre',
      simbolo: './public/simbologia/6.webp',
    },
    {
      cat_evento_id: 7,
      usuario_id: 7,
      nombre: 'Periodo de bajas de materias del Departamento Físico Matemáticas',
      fecha_inicio: new Date('2023-09-25'),
      fecha_fin: new Date('2023-09-30'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen7.webp',
      descripcion: 'Período de bajas de materias del Departamento Fisico Matematico',
      simbolo: './public/simbologia/7.webp',
    },
    {
      cat_evento_id: 8,
      usuario_id: 8,
      nombre: 'Reunión del Consejo de Posgrado de la Facultad de Ingeniería',
      fecha_inicio: new Date('2023-10-01'),
      fecha_fin: new Date('2023-10-01'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen8.webp',
      descripcion: 'Reunión del Consejo de Posgrado de la Facultad de Ingeniería',
      simbolo: './public/simbologia/8.webp',
    },
    {
      cat_evento_id: 9,
      usuario_id: 9,
      nombre: 'Período de altas y bajas de materias del DUI',
      fecha_inicio: new Date('2023-10-05'),
      fecha_fin: new Date('2023-10-10'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen9.webp',
      descripcion: 'Período de altas y bajas de materias del Departamento Universitario de Inglés',
      simbolo: './public/simbologia/9.webp',
    },
    {
      cat_evento_id: 10,
      usuario_id: 10,
      nombre: 'Sesión ordinaria del H. Consejo Técnico Consultivo.',
      fecha_inicio: new Date('2023-10-15'),
      fecha_fin: new Date('2023-10-15'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen10.webp',
      descripcion: 'Sesión ordinaria del H. Consejo Técnico Consultivo.',
      simbolo: './public/simbologia/10.webp',
    },
    {
      cat_evento_id: 11,
      usuario_id: 11,
      nombre: 'Inicio de cursos del DUI',
      fecha_inicio: new Date('2023-10-20'),
      fecha_fin: new Date('2023-10-20'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen11.webp',
      descripcion: 'Inicio de cursos del Departamento Universitario de Inglés',
      simbolo: './public/simbologia/11.webp',
    },
    {
      cat_evento_id: 12,
      usuario_id: 12,
      nombre: 'Día inhábil',
      fecha_inicio: new Date('2023-11-01'),
      fecha_fin: new Date('2023-11-01'),
      hipervinculos: [],
      imagen: './public/imagenes/imagen12.webp',
      descripcion: 'Día inhábil',
      simbolo: './public/simbologia/12.webp',
    },
]

export default Evento
